import type { VentureRecommendation, StartupIdea } from '@/app/studio/page'

/**
 * Serialize a recommendation + selected idea into a portable Markdown document.
 * Pure client-side — reads only data already in the VentureRecommendation payload.
 */
export function recommendationToMarkdown(
  rec: VentureRecommendation,
  selected: StartupIdea,
): string {
  const plan = rec.execution_plan
  const lines: string[] = []

  lines.push(`# ${plan?.startup_name ?? selected.name}`)
  if (plan?.value_proposition) lines.push(`\n_${plan.value_proposition}_`)

  lines.push(`\n## Venture Partner Memo\n\n${rec.final_memo}`)

  // Council reasoning
  if (rec.agent_outputs?.length) {
    lines.push(`\n## Council reasoning`)
    for (const a of rec.agent_outputs) {
      lines.push(`\n### ${a.agent_name}${a.score != null ? ` — ${a.score}/10` : ''}`)
      if (a.analysis) lines.push(a.analysis)
      if (a.key_findings?.length) {
        lines.push(`\n**Key findings**`)
        a.key_findings.forEach((f) => lines.push(`- ${f}`))
      }
      if (a.concerns?.length) {
        lines.push(`\n**Concerns**`)
        a.concerns.forEach((c) => lines.push(`- ${c}`))
      }
    }
  }

  // Scores
  lines.push(`\n## Scores`)
  lines.push(`- Overall: ${selected.startup_score}/10`)
  lines.push(`- Feasibility (Finance): ${selected.feasibility_score}/10`)
  lines.push(`- Founder fit (Founder-Fit): ${selected.founder_fit_score}/10`)
  lines.push(`- Market attractiveness (Trend): ${selected.market_attractiveness_score}/10`)

  if (plan) {
    lines.push(`\n## Lean canvas`)
    Object.entries(plan.lean_canvas ?? {}).forEach(([k, v]) =>
      lines.push(`- **${k.replace(/_/g, ' ')}:** ${v}`),
    )

    if (plan.thirty_day_roadmap?.length) {
      lines.push(`\n## 30-day roadmap`)
      plan.thirty_day_roadmap.forEach((m, i) => lines.push(`${i + 1}. ${m}`))
    }

    if (plan.marketing_strategy) lines.push(`\n## Marketing strategy\n\n${plan.marketing_strategy}`)
    if (plan.customer_acquisition_plan) lines.push(`\n## First customers\n\n${plan.customer_acquisition_plan}`)
    if (plan.elevator_pitch) lines.push(`\n## Elevator pitch\n\n${plan.elevator_pitch}`)
  }

  lines.push(`\n---\n_Generated by FounderOS — a council of AI agents._`)
  return lines.join('\n')
}

/** Trigger a client-side download of text as a file. */
export function downloadTextFile(filename: string, text: string): void {
  const blob = new Blob([text], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
